### ISSUE TITLE
GCRODR with flexible preconditioning

### ISSUE THREAD

**Issue by benno90** [hpddm/hpddm#100]
I would like to setup `GCRODR` with flexible preconditioning.
According to the  [manual](https://petsc.org/release/manualpages/KSP/KSPHPDDM/) you have to pass the option `-ksp_hpddm_variant flexible`. At the same time the manual says that this option is is superseded by `KSPSetPCSide(KSP ksp, PCSide side)`. However, `KSPSetPCSide` only gives you the options `PC_LEFT`, `PC_RIGHT` and `PC_SYMMETRIC`.
When I pass the `-ksp_hpddm_variant flexible` option, `PetscCall(KSPView(ksp,PETSC_VIEWER_STDOUT_WORLD))` gives me the following output:
```
KSP Object: 1 MPI process
type: hpddm
HPDDM type: gcrodr
precision: DOUBLE
deflation subspace attached? TRUE
deflation target: SM
maximum iterations=500, initial guess is zero
tolerances:  relative=1e-06, absolute=1e-50, divergence=10000.
right preconditioning
using UNPRECONDITIONED norm type for convergence test
```

Do I really have flexible preconditioning now?
It would be nice if flexible preconditioning would be confirmed in this info statement.

**Comment by prj-** [comment]
Indeed, PETSc uses different types for the same method depending on whether it handles variable preconditioning or not, e.g., `KSPGMRES` and `KSPFGMRES`. So it is easier to know if the method is flexible. I've addressed your comment in https://gitlab.com/petsc/petsc/-/merge_requests/6462. Hopefully, it will be easier to know if the `KSPHPDDM` submethod is flexible.

**Comment by benno90** [comment]
Many thanks for the quick reply - so i can assume that `GCRODR` uses flexible preconditioning when i pass the `-ksp_hpddm_variant flexible` option - it simply is currently not displayed?

**Comment by prj-** [comment]
Yes, that is correct. As long as you do not mix this option with `KSPSetPCSide()`, you should be safe. If you have an example where you think it is not the case, I would appreciate a reproducer.

**Comment by benno90** [comment]
ok - i will try a variable precondtioner and let you know if it works.
