### ISSUE TITLE
Handle PetscErrorCode from logging events

### ISSUE THREAD

**Issue by tisaac** [hpddm/hpddm#102]
Upcoming changes in PETSc are going to cause "nodiscard" warnings on `PetscLogEventBegin()` and `PetscLogEventEnd()` that are un-handled.

Can you please wrap lines like this in `PetscCall()` or discard them with "(void)"?

https://github.com/hpddm/hpddm/blob/d5f697e33343d9e13371f0d7c452afc0c87c42af/include/HPDDM_iterative.hpp#L724

**Comment by prj-** [comment]
My bad, it looks like I miss some of these indeed, thanks for the report.
