### ISSUE TITLE
Using HPDDM with PETSc

### ISSUE THREAD

**Issue by Aquan1412** [hpddm/hpddm#13]
Hello,
in your readme you mention that hpddm can be used via PETSc, however there is apparently no further documentation available. Also, when I check the compilation options of PETSc, there is no mention of hpddm. Is it still possible? If so, could you please tell me how to link those two packages?

**Comment by prj-** [comment]
Hello,
If you want to use HPDDM iterative methods (recycling or block methods) with PETSc preconditioners, you can have a look [here](https://github.com/hpddm/hpddm/blob/master/examples/petsc/ex32.c#L28) or [there](https://github.com/xuanvinhilb/PreMG/blob/master/PreMG_main.cpp#L25). Domain decomposition methods from HPDDM are not available within PETSc. For specific details (compilation or KSP setup), do not hesitate to get in touch with me via email.
