### ISSUE TITLE
Hang on MVAPICH2

### ISSUE THREAD

**Issue by cgcgcg** [hpddm/hpddm#19]
When running on MVAPICH2, I got a hang on `MPI_Igather`. (OpenMPI seemed unaffected.)
Using `Wrapper<downscaled_type<K>>::mpi_type()` instead of `MPI_DATATYPE_NULL` fixed it for me.
https://github.com/hpddm/hpddm/blob/e8639ff91fe0a5d462a62e8764355d7d5cd40de3/include/HPDDM_coarse_operator_impl.hpp#L1943-L1951

**Comment by prj-** [comment]
This _may_ be an upstream bug. I actually had to have this fixed in OpenMPI, cf. this ancient [changelog](https://github.com/open-mpi/ompi/blob/master/NEWS#L1916-L1918). Could you please let me know which version are you using? I'll try to reproduce this.

**Comment by cgcgcg** [comment]
This was a run on Cori@NERSC.
CRAY MPICH version 7.7.10 (ANL base 3.2)
MPI BUILD INFO : Built Mon Aug 19 15:12:38 2019 (git hash ff5d439) MT-G
MPI standard supported:       (3, 1)
Vendor:                       ('MPICH', (3, 2, 0))

**Comment by prj-** [comment]
I can reproduce a similar issue with Intel MPI 2018.0.3.222 (based on MPICH 3.2) as well.
```
Fatal error in PMPI_Igather: Invalid datatype, error stack:
PMPI_Igather(909):  MPI_Igather(sendbuf=0x24b9290, sendcount=12, sendtype=MPI_DOUBLE, recvbuf=(nil), recvcount=0, recvtype=MPI_DATATYPE_NULL, root=0, comm=comm=0x84000004, request=0x7ffdf10c1f90)
PMPI_Igather(788): Datatype for argument recvtype is a null datatype
```
This behaves properly when I switch to Intel MPI 2019.0.0.117 (based on MPICH 3.3b2), so I need to check `#if MPICH_NUMVERSION < 30300102`. Thanks for reporting this, I can't believe I didn't report this to upstream earlier...
