### ISSUE TITLE
HPDDM with PETSc/SLEPc on powerpc

### ISSUE THREAD

**Issue by koenstrien** [hpddm/hpddm#43]
I have recently been trying to install FreeFEM on Marconi100 powerpc and I have run into some troubles. Eventually we fixed the problem by forking the repository and changing `hpddm/include/HPDDM.hpp`. I will briefly descibe the problem and explain our fix. Hopefully you can use the information to find a neater/more permanent fix.

--
**Marconi100 system:**

Model: IBM Power AC922 (Whiterspoon)
Racks: 55 total (49 compute)
Nodes: 980
Processors: 2x16 cores IBM POWER9 AC922 at 2.6(3.1) GHz
Accelerators: 4 x NVIDIA Volta V100 GPUs/node, Nvlink 2.0, 16GB
Cores: 32 cores/node, Hyperthreading x4
RAM: 256 GB/node (242 usable)
Peak Performance: about 32 Pflop/s, 32 TFlops per node
Internal Network: Mellanox IB EDR DragonFly++
Disk Space: 8PB raw GPFS storage

**Compilers:**
spectrum_mpi - 10.3.1
gnu - 8.4.0

--

We tried different routes to do the install (hpddm via FreeFem, hpddm via PETSc, hppdm via PETSc via FreeFEM) but most routes eventually came to the same error of libpetsc.so havind undefined references to some lapack functions (error messages added below). However, libpetsc.so was correctly linked to liblapack.so. The problem is that liblapack.so has an underscore added to the function names (see other picture).

We have traced the source of this discrepancy to `hpddm/include/HPDDM.hpp::70` :
```
#if defined(__powerpc__) || defined(INTEL_MKL_VERSION)
# define HPDDM_F77(func) func
#else
# define HPDDM_F77(func) func ## _
#endif
```
We solve it by forking the branch and changing this to (https://github.com/DaanVanVugt/hpddm/blob/hpddm_underscore_powerpc_2/include/HPDDM.hpp)
```
#define HPDDM_F77(func) func ## _
```
and changing the repository and commit-id of hpddm in petsc/config/BuildSystem/config/packages/hppdm.py

I hope you can take a look and create a more general fix that could work for everyone. I think solving this should also fix the issue for installing directly from FreeFEM (with PETSc, SLEPc and hpddm)
If you require any more information from me just let me know!

![image](https://user-images.githubusercontent.com/66589602/111771257-c0c73d00-88ab-11eb-8d31-384021c86fed.png)
![image (1)](https://user-images.githubusercontent.com/66589602/111771415-f3713580-88ab-11eb-90cf-1b2cf696ec26.png)

.

**Comment by prj-** [comment]
Thanks for reporting this. Sorry, it has been a while since the last time I used PowerPC. Could you please confirm that in `arch-FreeFem/lib/petsc/conf/configure.log`, you have a line such as:
```
            Defined "BLASLAPACK_UNDERSCORE" to "1"
```
If it is not too much trouble for you, instead of:
```
#if defined(__powerpc__) || defined(INTEL_MKL_VERSION)
# define HPDDM_F77(func) func
#else
# define HPDDM_F77(func) func ## _
#endif
```
Could you please try:
```
#if (defined(__powerpc__) && !defined(PETSC_BLASLAPACK_UNDERSCORE)) || defined(INTEL_MKL_VERSION)
# define HPDDM_F77(func) func
#else
# define HPDDM_F77(func) func ## _
#endif
```

**Comment by koenstrien** [comment]
I see that you already added a commit. Thanks a lot for this! Indeed in the log I find `Defined "BLASLAPACK_UNDERSCORE" to "1"`. I have not yet tried whether the new commit works, but I will have to install the software again on a different account somewhere coming week. I will let you know then whether the commit has solved the issue for me. Thanks again!
