### ISSUE TITLE
OpenBLAS support?

### ISSUE THREAD

**Issue by catap** [hpddm/hpddm#81]
I've updated hpddm at MacPorts to the version 2.2.2 and discovered that additional patches is required to support OpenBLAS.

Without patch bellow it fails on attempt to link because `daxpby` function has wrong prefix.

Here the used patch. Anyway, I feel that it isn't right one. The right one should introduce `HPDDM_MKL` like macros to detect and support OpenBLAS.

```diff
diff --git include/HPDDM_BLAS.hpp include/HPDDM_BLAS.hpp
index 4062a1f..2abbc98 100644
--- include/HPDDM_BLAS.hpp
+++ include/HPDDM_BLAS.hpp
@@ -100,7 +100,7 @@ HPDDM_GENERATE_EXTERN_BLAS_COMPLEX(k, std::complex<__fp16>, h, __fp16)
 #  endif
 #  if HPDDM_MKL || (defined(__APPLE__) && !defined(PETSC_HAVE_F2CBLASLAPACK))
 #   if !HPDDM_MKL
-#    define HPDDM_PREFIX_AXPBY(func) catlas_ ## func
+#    define HPDDM_PREFIX_AXPBY(func) cblas_ ## func
 #   else
 HPDDM_GENERATE_EXTERN_MKL_EXTENSIONS(c, std::complex<float>, s, float)
 HPDDM_GENERATE_EXTERN_MKL_EXTENSIONS(z, std::complex<double>, d, double)
```

**Comment by prj-** [comment]
Thanks for the report. I confirm I can reproduce the issue. I have a tentative fix at https://github.com/hpddm/hpddm/pull/82. Could you please confirm this fixes the build on your end as well? You will have to set `OPENBLAS_LIBS` accordingly.

**Comment by catap** [comment]
Pierre, thanks for path. I'd like to confirm that it works on my end.

**Comment by prj-** [comment]
Thank you for the confirmation. I wasn't sure at first I understood your message properly, but I'm seeing that you are using the patch from the PR in https://github.com/macports/macports-ports/pull/16842, so I'm guessing it's working OK! I will merge the PR today.
