### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [hpddm/hpddm#84]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [buildTwo](https://github.com/hpddm/hpddm/blob/0265ae1e37c6682d091927213897b63c378f6398/include/HPDDM_preconditioner.hpp#L181 "buildTwo function")
- [solveEVP](https://github.com/hpddm/hpddm/blob/0265ae1e37c6682d091927213897b63c378f6398/include/HPDDM_dense.hpp#L75 "solveEVP function")
- [Mumps](https://github.com/hpddm/hpddm/blob/0265ae1e37c6682d091927213897b63c378f6398/include/HPDDM_MUMPS.hpp#L77 "Destructor for Mumps")

**Comment by prj-** [comment]
Good catch, thanks. Should hopefully be fixed in https://github.com/hpddm/hpddm/pull/87.
