### ISSUE TITLE
Reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [hpddm/hpddm#85]
I would like to point out that identifiers like “[`_A`](https://github.com/hpddm/hpddm/blob/0265ae1e37c6682d091927213897b63c378f6398/include/HPDDM_Elemental.hpp#L49 "Update candidate")” and “[`_HPDDM_H_`](https://github.com/hpddm/hpddm/blob/0265ae1e37c6682d091927213897b63c378f6398/interface/HPDDM.h#L24 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by prj-** [comment]
I've wanted to fix this for quite some years, but never took the actual time to do it. Now that there is an open issue, I will give it a shot in the upcoming days.

**Comment by elfring** [comment]
Thanks for your renaming of some affected identifiers.
* [Variable names](https://github.com/hpddm/hpddm/commit/24981edec4d45e3b8f397b01ec5a1da64d0769bf#diff-48609f14ae97c078799bd2a57c0720fdcca1d100e2fc690e36e4eca4fe1c2faaR49 "Switches from leading to trailing underscore.")
* [Include guards](https://github.com/hpddm/hpddm/commit/765bbca54f0bf24bf4c55392acfcfdfeab6701c5 "Removes leading underscore of header guards.")


:thinking: [Some identifiers will need further development considerations](https://github.com/hpddm/hpddm/blob/24981edec4d45e3b8f397b01ec5a1da64d0769bf/include/HPDDM_wrapper.hpp#L119 "Further update candidates") for this issue because of [the usage of double underscores](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
