### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [hpddm/hpddm#86]
Would you like to [wrap any pointers](https://github.com/hpddm/hpddm/blob/0265ae1e37c6682d091927213897b63c378f6398/include/HPDDM_dense.hpp#L104 "Update candidate: solveEVP()") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by prj-** [comment]
No, I know too little about its implementation and I don't see any potential benefits.

**Comment by elfring** [comment]
:thought_balloon:
* Are you familiar with [the programming term “exception safety”](https://en.wikipedia.org/wiki/Exception_safety "Documentation")?
* How do you think about to take [the C++ guideline “R.11: Avoid calling new and delete explicitly”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation") better into account?

**Comment by prj-** [comment]
Could you share a reproducer exhibiting a memory leak/error due to a naked `new`/`delete`? If not, my points still hold.

**Comment by elfring** [comment]
:thought_balloon: Do you care for run time consequences if [the exception “std::bad_alloc”](https://en.cppreference.com/w/cpp/memory/new/bad_alloc "Description for std::bad_alloc") would be thrown?

**Comment by prj-** [comment]
You are not answering to my previous question, so I guess you don't have such a reproducer.
Unfortunately, I do not currently catch/handle gracefully (most) exceptions/errors from either the C++ standard library, MPI, or BLAS/LAPACK. MPI errors are much more frequent than C++ exceptions, so this is more important, IMHO.

**Comment by elfring** [comment]
>You are not answering to my previous question, so I guess you don't have such a reproducer.

The referenced source code contains sufficient examples for known software weaknesses.
“Reproducers” were discussed by other information sources already, weren't they?
What does hinder you to benefit any more from C++ Core Guidelines? :thinking:


>Unfortunately, I do not currently catch/handle gracefully (most) exceptions/errors …

:thought_balloon: I hope that such a programming habit can be adjusted considerably.

**Comment by prj-** [comment]
> “Reproducers” were discussed by other information sources already, weren't they?

Well, you open an issue on this specific repository, so please provide a specific reproducer.

**Comment by elfring** [comment]
Do you find the following source code example [easier to understand](https://en.cppreference.com/w/cpp/memory/new "Documentation for low level memory management")?

```C++
#include <new>

void my_test(void)
{
char* x = new char[1234567890];
int* y = new int;
throw std::bad_alloc{};
// Perform further data processing
delete y;
delete[] x;
}
```


Smart pointers are available to [fix the shown programming mistake](https://cwe.mitre.org/data/definitions/401.html "CWE-401: Missing Release of Memory after Effective Lifetime").

**Comment by prj-** [comment]
I don't think you are getting my point. Until you can exhibit such a faulty behavior with some specific code from this repository, there is no real purpose going further.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/owning-memory.html "Checking handling of pointers")?

**Comment by prj-** [comment]
No.
