### ISSUE TITLE
Using iterative solver for subdomain through FreeFEM interface

### ISSUE THREAD

**Issue by ktkimit** [hpddm/hpddm#99]
It looks like the default solver for the subdomain is set to direct solver. However, I want to change it to iterative solver. I am using FreeFEM as an interface to hpddm. Is there a document or simple example/tutorial explaining how to change the subdomain solver to iterative solver in FreeFEM/hpddm environment?

**Comment by prj-** [comment]
This is currently only possible if you use HPDDM through PETSc. In which case, you can use options such as `-pc_hpddm_levels_1_sub_pc_type ilu`, either on the command line, or through `set(A, sparams = "...")` where `A` is a previously created `Mat`.
